server:
  port: 84

spring:
  application:
    name: Sentinel-Order
  cloud:
    nacos:
      discovery:
        server-addr: cying.com:8848
    sentinel:
      transport:
        dashboard: cying.com:1314
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"

config:
  baseurl: "http://Sentinel-Provider"