server:
  port: 8401

spring:
  application:
    name: SENTINEL-PROVIDER
  cloud:
    nacos:
      discovery:
        server-addr: Cying.com:8848
    sentinel:
      transport:
        dashboard: Cying.com:1314
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"