server:
  port: 9002

spring:
  application:
    name: Alibaba-Payment-Provider
  cloud:
    nacos:
      discovery:
        server-addr: Cying.com:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"