server:
  port: 8001

spring:
  application:
    name: Hystrix-Payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://Cying.com:7001/eureka
  instance:
    instance-id: HystrixPay