server:
  port: 8001

spring:
  application:
    name: Payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cying.com:7001/eureka
  instance:
    instance-id: payment-8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cying.entities