server:
  port: 80

spring:
  application:
    name: Open-Feign-Order

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://Cying.com:7001/eureka/,http://Cying.com:7002/eureka/
  instance:
    instance-id: OpenFeign

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000